compileStructCode:typedef.c
	gcc typedef.c -o typedef

compileUnionCode:union.c
	gcc union.c -o union

compileEnumCode:Enums.c
	gcc Enums.c -o Enums

cleanStructCode:
	rm typedef

cleanUnionCode:
	rm union

cleanEnumCode:
	rm Enums